#!/bin/bash

#
# Cleanup a media directory by removing all thumbnail images and empty
# files/directories
#
#  Usage:
#     cleanup media-dir
#

#
# WARNING: Specifying a wrong directory will wipe off all images!
#
echo "Removing thumbnail images..."
find $@ -name \*.jpg -delete -print

echo "Removing non-media files..."
find $@ -type f \! -iname \*.mp3    \
             -a \! -iname \*.mp4    \
             -a \! -iname \*.wma    \
             -a \! -iname \*.wav    \
             -a \! -iname \*.ac3    \
             -a \! -iname \*.rm     \
             -a \! -iname \*.cdg    \
             -a \! -iname \*.flac   \
             -a \! -iname \*.m4a -delete -print

echo "Removing empty directories..."
find $@ -empty -delete -print

